In [2]:
import numpy as np
import pandas as pd

In [3]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

In [4]:
movies.head(5)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [5]:
movies.shape

(4803, 20)

In [6]:
credits.shape

(4803, 4)

In [7]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [8]:
movies = movies.merge(credits,on='title')

In [9]:
movies.shape

(4809, 23)

In [10]:
movies.head()
# budget
# homepage
# id
# original_language
# original_title
# popularity
# production_comapny
# production_countries
# release-date(not sure)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [11]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 901.7+ KB

In [12]:
movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [13]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [14]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [15]:
movies.duplicated().sum()

0

In [16]:
movies.dropna(inplace=True)

In [17]:
movies['genres'][0]

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [18]:
import ast

In [19]:

ast.literal_eval('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]')

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [20]:
def convert(text):
    L = []
    for i in ast.literal_eval(text):
        L.append(i['name']) 
    return L

In [21]:
movies.dropna(inplace=True)

In [22]:
movies['genres'] = movies['genres'].apply(convert)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [23]:
movies['keywords'] = movies['keywords'].apply(convert)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [24]:
def convert3(text):
    L = []
    counter = 0
    for i in ast.literal_eval(text):
        if counter < 3:
            L.append(i['name'])
        counter+=1
    return L

In [25]:
movies['cast'] = movies['cast'].apply(convert)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [26]:
movies['cast'] = movies['cast'].apply(lambda x:x[0:3])

In [27]:
def fetch_director(text):
    L = []
    for i in ast.literal_eval(text):
        if i['job'] == 'Director':
            L.append(i['name'])
    return L

In [28]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [29]:
#movies['overview'] = movies['overview'].apply(lambda x:x.split())
movies.sample(5)

,movie_id,title,overview,genres,keywords,cast,crew
617,26428,Agora,"A historical drama set in Roman Egypt, concern...","[Adventure, Drama, History]","[christianity, philosophy, egypt, new love, wa...","[Rachel Weisz, Max Minghella, Oscar Isaac]",[Alejandro Amenábar]
275,180,Minority Report,John Anderton is a top 'Precrime' cop in the l...,"[Action, Thriller, Science Fiction, Mystery]","[self-fulfilling prophecy, washington d.c., ev...","[Tom Cruise, Colin Farrell, Samantha Morton]",[Steven Spielberg]
3314,33542,Rumble in the Bronx,Keong comes from Hong Kong to visit New York f...,"[Crime, Action, Comedy, Thriller]","[new york, martial arts, supermarket, gang war...","[Jackie Chan, Anita Mui, Françoise Yip]",[Stanley Tong]
4530,84401,Sholem Aleichem: Laughing In The Darkness,A riveting portrait of the great writer whose ...,[Documentary],[],"[Rachel Dratch, Hillel Halkin, Jason Kravitz]",[Joseph Dorman]
726,9384,Starsky & Hutch,"Join uptight David Starsky and laid-back Ken ""...","[Comedy, Crime]","[informant, jumping from a rooftop, surveillan...","[Ben Stiller, Owen Wilson, Snoop Dogg]",[Todd Phillips]

In [30]:
def collapse(L):
    L1 = []
    for i in L:
        L1.append(i.replace(" ",""))
    return L1

In [31]:
movies['cast'] = movies['cast'].apply(collapse)
movies['crew'] = movies['crew'].apply(collapse)
movies['genres'] = movies['genres'].apply(collapse)
movies['keywords'] = movies['keywords'].apply(collapse)

In [32]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [33]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [34]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [35]:
new = movies.drop(columns=['overview','genres','keywords','cast','crew'])
#new.head()

In [36]:
new['tags'] = new['tags'].apply(lambda x: " ".join(x))
new.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [37]:
new['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

In [38]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [39]:
vector = cv.fit_transform(new['tags']).toarray()

In [40]:
vector.shape

(4806, 5000)

In [41]:
from sklearn.metrics.pairwise import cosine_similarity

In [42]:
similarity = cosine_similarity(vector)

In [43]:
similarity

array([[1.        , 0.08964215, 0.06071767, ..., 0.02519763, 0.0277885 ,
        0.        ],
       [0.08964215, 1.        , 0.06350006, ..., 0.02635231, 0.        ,
        0.        ],
       [0.06071767, 0.06350006, 1.        , ..., 0.02677398, 0.        ,
        0.        ],
       ...,
       [0.02519763, 0.02635231, 0.02677398, ..., 1.        , 0.07352146,
        0.04774099],
       [0.0277885 , 0.        , 0.        , ..., 0.07352146, 1.        ,
        0.05264981],
       [0.        , 0.        , 0.        , ..., 0.04774099, 0.05264981,
        1.        ]])

In [44]:
new[new['title'] == 'The Lego Movie'].index[0]

744

In [45]:
list(enumerate(similarity[0]))

[(0, 1.0),
 (1, 0.08964214570007951),
 (2, 0.060717674071891624),
 (3, 0.03984095364447979),
 (4, 0.18257418583505536),
 (5, 0.1183452670827877),
 (6, 0.023218173010628604),
 (7, 0.1763834207376394),
 (8, 0.06388765649999398),
 (9, 0.07733088933397005),
 (10, 0.11769797726729994),
 (11, 0.081199794294115),
 (12, 0.09583148474999097),
 (13, 0.04733810683311508),
 (14, 0.11428571428571427),
 (15, 0.05096471914376255),
 (16, 0.08226127456606226),
 (17, 0.15026857675938213),
 (18, 0.11194341570991125),
 (19, 0.08728715609439694),
 (20, 0.058167505074711086),
 (21, 0.09416472308615166),
 (22, 0.06900655593423542),
 (23, 0.09759000729485331),
 (24, 0.0563436169819011),
 (25, 0.03877833671647406),
 (26, 0.17142857142857143),
 (27, 0.18752289237539815),
 (28, 0.12555296411486888),
 (29, 0.07100716024967263),
 (30, 0.07319250547113999),
 (31, 0.15971914124998493),
 (32, 0.09116846116771035),
 (33, 0.1057361065275362),
 (34, 0.0),
 (35, 0.11065666703449761),
 (36, 0.19194297398747862),
 (37, 0.08451542547285165),
 (38, 0.0628970902033151),
 (39, 0.08827348295047496),
 (40, 0.0563436169819011),
 (41, 0.14638501094227999),
 (42, 0.0),
 (43, 0.09759000729485333),
 (44, 0.040996003084539386),
 (45, 0.09116846116771035),
 (46, 0.17654696590094993),
 (47, 0.2164218276749025),
 (48, 0.06776309271789384),
 (49, 0.06388765649999398),
 (50, 0.12344267996967351),
 (51, 0.08586775814821836),
 (52, 0.1449427589131121),
 (53, 0.04931136727215379),
 (54, 0.035245368842512066),
 (55, 0.07655590023509526),
 (56, 0.14414999403128942),
 (57, 0.028988551782622416),
 (58, 0.04733810683311508),
 (59, 0.08024108542850393),
 (60, 0.028988551782622416),
 (61, 0.21622499104693413),
 (62, 0.08199200616907877),
 (63, 0.09200874124564722),
 (64, 0.03138824102871722),
 (65, 0.020965696734438367),
 (66, 0.02492223931396134),
 (67, 0.17928429140015903),
 (68, 0.13259870882635919),
 (69, 0.0520265981714472),
 (70, 0.081199794294115),
 (71, 0.08226127456606226),
 (72, 0.12344267996967351),
 (73, 0.03779644730092272),
 (74, 0.2267786838055363),
 (75, 0.09258200997725513),
 (76, 0.07824607964359516),
 (77, 0.014824986333222025),
 (78, 0.05345224838248488),
 (79, 0.07824607964359516),
 (80, 0.03450327796711771),
 (81, 0.11710800875382396),
 (82, 0.08336550215650926),
 (83, 0.22190115272469205),
 (84, 0.1456438162508838),
 (85, 0.10631548679075009),
 (86, 0.08827348295047496),
 (87, 0.11595420713048966),
 (88, 0.09107651110783743),
 (89, 0.06146576398025575),
 (90, 0.06506000486323554),
 (91, 0.15971914124998493),
 (92, 0.07100716024967263),
 (93, 0.05039526306789696),
 (94, 0.16574838603294897),
 (95, 0.1246111965698067),
 (96, 0.08964214570007951),
 (97, 0.07476671794188401),
 (98, 0.08827348295047496),
 (99, 0.029880715233359837),
 (100, 0.07377111135633174),
 (101, 0.08827348295047496),
 (102, 0.11194341570991125),
 (103, 0.08877935232369503),
 (104, 0.05884898863364997),
 (105, 0.10811249552346706),
 (106, 0.0447773662839645),
 (107, 0.09200874124564722),
 (108, 0.16903085094570328),
 (109, 0.07968190728895957),
 (110, 0.024397501823713332),
 (111, 0.15430334996209188),
 (112, 0.09107651110783743),
 (113, 0.052796367734845466),
 (114, 0.052796367734845466),
 (115, 0.05413319619607667),
 (116, 0.057142857142857134),
 (117, 0.060717674071891624),
 (118, 0.017622684421256033),
 (119, 0.048795003647426664),
 (120, 0.0),
 (121, 0.09107651110783743),
 (122, 0.09583148474999097),
 (123, 0.12198750911856666),
 (124, 0.06837634587578277),
 (125, 0.07985957062499247),
 (126, 0.11595420713048966),
 (127, 0.1357241785076592),
 (128, 0.0),
 (129, 0.10559273546969093),
 (130, 0.03194382824999699),
 (131, 0.1126872339638022),
 (132, 0.045584230583855176),
 (133, 0.033149677206589796),
 (134, 0.13522468075656266),
 (135, 0.0),
 (136, 0.025482359571881275),
 (137, 0.034324965259398446),
 (138, 0.08226127456606226),
 (139, 0.10821091383745127),
 (140, 0.05096471914376255),
 (141, 0.11338934190276816),
 (142, 0.09759000729485331),
 (143, 0.06965451903188581),
 (144, 0.055577001437672836),
 (145, 0.02258769757263128),
 (146, 0.017251638983558856),
 (147, 0.06277648205743444),
 (148, 0.1057361065275362),
 (149, 0.17313746213992204),
 (150, 0.18869127060994534),
 (151, 0.20498001542269692),
 (152, 0.06388765649999398),
 (153, 0.086568731069961),
 (154, 0.033149677206589796),
 (155, 0.0),
 (156, 0.06658451424277127),
 (157, 0.1057361065275362),
 (158, 0.15289415743128765),
 (159, 0.06761234037828133),
 (160, 0.09694584179118515),
 (161, 0.035245368842512066),
 (162, 0.03688555567816587),
 (163, 0.05413319619607667),
 (164, 0.09416472308615166),
 (165, 0.04984447862792268),
 (166, 0.11952286093343935),
 (167, 0.06900655593423542),
 (168, 0.16035674514745463),
 (169, 0.11952286093343936),
 (170, 0.09200874124564722),
 (171, 0.029424494316824985),
 (172, 0.15118578920369088),
 (173, 0.024397501823713332),
 (174, 0.11115400287534567),
 (175, 0.0515539262226467),
 (176, 0.030860669992418377),
 (177, 0.0),
 (178, 0.02577696311132335),
 (179, 0.07559289460184544),
 (180, 0.023904572186687872),
 (181, 0.02344036154692477),
 (182, 0.10690449676496976),
 (183, 0.07466533929465573),
 (184, 0.18257418583505539),
 (185, 0.055577001437672836),
 (186, 0.040697846377823976),
 (187, 0.14085904245475275),
 (188, 0.02258769757263128),
 (189, 0.08199200616907877),
 (190, 0.08386278693775347),
 (191, 0.0515539262226467),
 (192, 0.0),
 (193, 0.08728715609439694),
 (194, 0.0),
 (195, 0.06506000486323554),
 (196, 0.05884898863364997),
 (197, 0.048795003647426664),
 (198, 0.059761430466719674),
 (199, 0.11720180773462385),
 (200, 0.07755667343294811),
 (201, 0.0),
 (202, 0.03450327796711771),
 (203, 0.08827348295047496),
 (204, 0.02672612419124244),
 (205, 0.08199200616907877),
 (206, 0.09694584179118515),
 (207, 0.0857142857142857),
 (208, 0.1690308509457033),
 (209, 0.03877833671647406),
 (210, 0.05484084971070818),
 (211, 0.02742042485535409),
 (212, 0.07644707871564382),
 (213, 0.0654653670707977),
 (214, 0.028988551782622416),
 (215, 0.07396705090823068),
 (216, 0.06506000486323554),
 (217, 0.04643634602125721),
 (218, 0.042257712736425826),
 (219, 0.06629935441317959),
 (220, 0.18832944617230335),
 (221, 0.024655683636076894),
 (222, 0.09035079029052512),
 (223, 0.08336550215650926),
 (224, 0.06338656910463875),
 (225, 0.052164053095730106),
 (226, 0.029880715233359837),
 (227, 0.09258200997725513),
 (228, 0.12598815766974242),
 (229, 0.07913425882489307),
 (230, 0.08877935232369503),
 (231, 0.0),
 (232, 0.11952286093343935),
 (233, 0.10811249552346706),
 (234, 0.06776309271789384),
 (235, 0.060717674071891624),
 (236, 0.09759000729485331),
 (237, 0.07049073768502413),
 (238, 0.12777531299998796),
 (239, 0.1109741904046188),
 (240, 0.05096471914376255),
 (241, 0.08964214570007951),
 (242, 0.09416472308615166),
 (243, 0.09968895725584535),
 (244, 0.06277648205743444),
 (245, 0.09107651110783743),
 (246, 0.06601782722034923),
 (247, 0.0),
 (248, 0.04733810683311508),
 (249, 0.14414999403128942),
 (250, 0.0),
 (251, 0.042257712736425826),
 (252, 0.022792115291927588),
 (253, 0.06601782722034923),
 (254, 0.08336550215650926),
 (255, 0.0),
 (256, 0.08199200616907877),
 (257, 0.08696565534786725),
 (258, 0.02344036154692477),
 (259, 0.06388765649999398),
 (260, 0.25110592822973776),
 (261, 0.025482359571881275),
 (262, 0.07476671794188401),
 (263, 0.1057361065275362),
 (264, 0.0),
 (265, 0.029424494316824985),
 (266, 0.11115400287534567),
 (267, 0.07559289460184544),
 (268, 0.02742042485535409),
 (269, 0.033149677206589796),
 (270, 0.1031078524452934),
 (271, 0.0791945516022682),
 (272, 0.030860669992418377),
 (273, 0.024655683636076894),
 (274, 0.08058229640253803),
 (275, 0.12555296411486888),
 (276, 0.06761234037828133),
 (277, 0.06601782722034923),
 (278, 0.1031078524452934),
 (279, 0.1031078524452934),
 (280, 0.0),
 (281, 0.07319250547113999),
 (282, 0.030860669992418377),
 (283, 0.0),
 (284, 0.020203050891044214),
 (285, 0.022792115291927588),
 (286, 0.02258769757263128),
 (287, 0.02742042485535409),
 (288, 0.0),
 (289, 0.05039526306789696),
 (290, 0.06761234037828133),
 (291, 0.0563436169819011),
 (292, 0.10141851056742199),
 (293, 0.03194382824999699),
 (294, 0.11952286093343935),
 (295, 0.10968169942141635),
 (296, 0.040120542714251965),
 (297, 0.04829452884162951),
 (298, 0.0),
 (299, 0.04161251892882394),
 (300, 0.18708286933869706),
 (301, 0.18182745801939793),
 (302, 0.060717674071891624),
 (303, 0.028988551782622416),
 (304, 0.07207499701564471),
 (305, 0.1932024558334913),
 (306, 0.09416472308615166),
 (307, 0.10460520656316097),
 (308, 0.07049073768502413),
 (309, 0.06629935441317959),
 (310, 0.036037498507822355),
 (311, 0.1564921592871903),
 (312, 0.10968169942141635),
 (313, 0.07968190728895957),
 (314, 0.0),
 (315, 0.09107651110783743),
 (316, 0.0),
 (317, 0.0),
 (318, 0.0),
 (319, 0.07207499701564471),
 (320, 0.033806170189140665),
 (321, 0.0),
 (322, 0.22230800575069135),
 (323, 0.033149677206589796),
 (324, 0.026398183867422733),
 (325, 0.11065666703449761),
 (326, 0.05884898863364997),
 (327, 0.028988551782622416),
 (328, 0.0),
 (329, 0.08336550215650926),
 (330, 0.1126872339638022),
 (331, 0.04984447862792268),
 (332, 0.14285714285714285),
 (333, 0.030860669992418377),
 (334, 0.10690449676496976),
 (335, 0.0563436169819011),
 (336, 0.07377111135633174),
 (337, 0.024147264420814756),
 (338, 0.0),
 (339, 0.057142857142857134),
 (340, 0.052164053095730106),
 (341, 0.061721339984836754),
 (342, 0.13662601021279464),
 (343, 0.022792115291927588),
 (344, 0.03138824102871722),
 (345, 0.02366905341655754),
 (346, 0.0),
 (347, 0.0),
 (348, 0.06761234037828133),
 (349, 0.09258200997725513),
 (350, 0.05484084971070818),
 (351, 0.0),
 (352, 0.029424494316824985),
 (353, 0.023904572186687872),
 (354, 0.0),
 (355, 0.040120542714251965),
 (356, 0.09258200997725513),
 (357, 0.0),
 (358, 0.06629935441317959),
 (359, 0.03450327796711771),
 (360, 0.0),
 (361, 0.0563436169819011),
 (362, 0.09759000729485331),
 (363, 0.09116846116771035),
 (364, 0.026082026547865053),
 (365, 0.081199794294115),
 (366, 0.059761430466719674),
 (367, 0.0),
 (368, 0.13522468075656266),
 (369, 0.09258200997725513),
 (370, 0.0563436169819011),
 (371, 0.1031078524452934),
 (372, 0.05345224838248488),
 (373, 0.18018749253911176),
 (374, 0.04438967616184752),
 (375, 0.0432843655349805),
 (376, 0.048795003647426664),
 (377, 0.0),
 (378, 0.0),
 (379, 0.05345224838248487),
 (380, 0.02817180849095055),
 (381, 0.09035079029052512),
 (382, 0.0),
 (383, 0.0515539262226467),
 (384, 0.03253000243161777),
 (385, 0.0),
 (386, 0.024147264420814756),
 (387, 0.02742042485535409),
 (388, 0.0),
 (389, 0.10141851056742199),
 (390, 0.02817180849095055),
 (391, 0.06149400462680908),
 (392, 0.03138824102871722),
 (393, 0.0),
 (394, 0.026082026547865053),
 (395, 0.057142857142857134),
 (396, 0.02366905341655754),
 (397, 0.055577001437672836),
 (398, 0.0),
 (399, 0.02577696311132335),
 (400, 0.10350983390135313),
 (401, 0.03194382824999699),
 (402, 0.061721339984836754),
 (403, 0.11002971203391539),
 (404, 0.06761234037828133),
 (405, 0.030860669992418377),
 (406, 0.021821789023599235),
 (407, 0.026082026547865053),
 (408, 0.035245368842512066),
 (409, 0.0),
 (410, 0.10079052613579392),
 (411, 0.05884898863364997),
 (412, 0.1019294382875251),
 (413, 0.1389425035941821),
 (414, 0.033149677206589796),
 (415, 0.07126966450997983),
 (416, 0.0563436169819011),
 (417, 0.033806170189140665),
 (418, 0.03779644730092272),
 (419, 0.07644707871564382),
 (420, 0.12888481555661674),
 (421, 0.0),
 (422, 0.14754222271266348),
 (423, 0.052164053095730106),
 (424, 0.04040610178208843),
 (425, 0.07100716024967263),
 (426, 0.06195121541733006),
 (427, 0.029424494316824985),
 (428, 0.059350694118669806),
 (429, 0.0),
 (430, 0.052796367734845466),
 (431, 0.02577696311132335),
 (432, 0.12598815766974242),
 (433, 0.033149677206589796),
 (434, 0.0),
 (435, 0.03984095364447979),
 (436, 0.0),
 (437, 0.028988551782622416),
 (438, 0.028571428571428567),
 (439, 0.030860669992418377),
 (440, 0.028571428571428567),
 (441, 0.030358837035945812),
 (442, 0.048795003647426664),
 (443, 0.05884898863364997),
 (444, 0.0),
 (445, 0.028571428571428567),
 (446, 0.02577696311132335),
 (447, 0.023904572186687872),
 (448, 0.026082026547865053),
 (449, 0.05797710356524483),
 (450, 0.026398183867422733),
 (451, 0.026398183867422733),
 (452, 0.03194382824999699),
 (453, 0.02672612419124244),
 (454, 0.12327841818038447),
 (455, 0.024655683636076894),
 (456, 0.0703210846407743),
 (457, 0.08696565534786725),
 (458, 0.04733810683311508),
 (459, 0.036037498507822355),
 (460, 0.028571428571428567),
 (461, 0.1938916835823703),
 (462, 0.0),
 (463, 0.035245368842512066),
 (464, 0.0),
 (465, 0.0),
 (466, 0.2114722130550724),
 (467, 0.09116846116771035),
 (468, 0.030358837035945812),
 (469, 0.0703210846407743),
 (470, 0.04931136727215379),
 (471, 0.08336550215650926),
 (472, 0.08451542547285165),
 (473, 0.1019294382875251),
 (474, 0.0),
 (475, 0.06837634587578276),
 (476, 0.10811249552346706),
 (477, 0.0),
 (478, 0.03984095364447979),
 (479, 0.09508728264112047),
 (480, 0.052164053095730106),
 (481, 0.0),
 (482, 0.030358837035945812),
 (483, 0.1301200097264711),
 (484, 0.03450327796711771),
 (485, 0.0563436169819011),
 (486, 0.05855400437691198),
 (487, 0.14098147537004826),
 (488, 0.07606982611289638),
 (489, 0.0),
 (490, 0.15118578920369088),
 (491, 0.09116846116771035),
 (492, 0.06277648205743444),
 (493, 0.01951800145897066),
 (494, 0.0),
 (495, 0.2162249910469341),
 (496, 0.0),
 (497, 0.0),
 (498, 0.07207499701564471),
 (499, 0.0),
 (500, 0.028571428571428567),
 (501, 0.0880237696271323),
 (502, 0.1546617786679401),
 (503, 0.08336550215650926),
 (504, 0.0),
 (505, 0.14754222271266348),
 (506, 0.03688555567816587),
 (507, 0.2484646732989441),
 (508, 0.11595420713048966),
 (509, 0.02577696311132335),
 (510, 0.10559273546969093),
 (511, 0.09583148474999097),
 (512, 0.060717674071891624),
 (513, 0.11769797726729994),
 (514, 0.059761430466719674),
 (515, 0.027066598098038335),
 (516, 0.02577696311132335),
 (517, 0.0),
 (518, 0.055577001437672836),
 (519, 0.0),
 (520, 0.0),
 (521, 0.028988551782622416),
 (522, 0.0),
 (523, 0.052164053095730106),
 (524, 0.0),
 (525, 0.02492223931396134),
 (526, 0.0),
 (527, 0.0),
 (528, 0.024147264420814756),
 (529, 0.13041013273932528),
 (530, 0.10141851056742199),
 (531, 0.05039526306789696),
 (532, 0.023002185311411804),
 (533, 0.07049073768502413),
 (534, 0.08451542547285165),
 (535, 0.10968169942141635),
 (536, 0.07733088933397005),
 (537, 0.07049073768502413),
 (538, 0.0),
 (539, 0.26089696604360174),
 (540, 0.0563436169819011),
 (541, 0.06900655593423541),
 (542, 0.04040610178208843),
 (543, 0.07824607964359516),
 (544, 0.060717674071891624),
 (545, 0.028571428571428567),
 (546, 0.07207499701564471),
 (547, 0.08964214570007951),
 (548, 0.0),
 (549, 0.12461119656980668),
 (550, 0.028571428571428567),
 (551, 0.0447773662839645),
 (552, 0.0),
 (553, 0.03194382824999699),
 (554, 0.0),
 (555, 0.0497245158098847),
 (556, 0.028988551782622416),
 (557, 0.1449427589131121),
 (558, 0.0),
 (559, 0.03253000243161777),
 (560, 0.04643634602125721),
 (561, 0.03688555567816587),
 (562, 0.0),
 (563, 0.02742042485535409),
 (564, 0.10141851056742199),
 (565, 0.04600437062282361),
 (566, 0.02492223931396134),
 (567, 0.030358837035945812),
 (568, 0.1449427589131121),
 (569, 0.024147264420814756),
 (570, 0.07559289460184544),
 (571, 0.021821789023599235),
 (572, 0.08518354199999197),
 (573, 0.02258769757263128),
 (574, 0.024397501823713332),
 (575, 0.057142857142857134),
 (576, 0.028988551782622416),
 (577, 0.15430334996209188),
 (578, 0.04829452884162951),
 (579, 0.12344267996967351),
 (580, 0.02519763153394848),
 (581, 0.16265001215808886),
 (582, 0.24147264420814754),
 (583, 0.052164053095730106),
 (584, 0.05096471914376255),
 (585, 0.0),
 (586, 0.045584230583855176),
 (587, 0.08017837257372731),
 (588, 0.028988551782622416),
 (589, 0.09862273454430757),
 (590, 0.035245368842512066),
 (591, 0.07824607964359516),
 (592, 0.027066598098038335),
 (593, 0.0),
 (594, 0.055577001437672836),
 (595, 0.13533299049019168),
 (596, 0.09658905768325902),
 (597, 0.05797710356524483),
 (598, 0.03984095364447979),
 (599, 0.03363839659676322),
 (600, 0.07244179326244427),
 (601, 0.03688555567816587),
 (602, 0.04517539514526256),
 (603, 0.057142857142857134),
 (604, 0.06761234037828133),
 (605, 0.0),
 (606, 0.0),
 (607, 0.06716604942594674),
 (608, 0.0),
 (609, 0.047809144373375745),
 (610, 0.06060915267313264),
 (611, 0.02492223931396134),
 (612, 0.07100716024967263),
 (613, 0.03779644730092272),
 (614, 0.060717674071891624),
 (615, 0.033149677206589796),
 (616, 0.0),
 (617, 0.055577001437672836),
 (618, 0.09862273454430757),
 (619, 0.0),
 (620, 0.0),
 (621, 0.07049073768502413),
 (622, 0.02219483808092376),
 (623, 0.0),
 (624, 0.11952286093343936),
 (625, 0.03194382824999699),
 (626, 0.08696565534786725),
 (627, 0.11633501014942217),
 (628, 0.0),
 (629, 0.04984447862792268),
 (630, 0.025482359571881275),
 (631, 0.02742042485535409),
 (632, 0.08336550215650926),
 (633, 0.023904572186687872),
 (634, 0.0857142857142857),
 (635, 0.07476671794188401),
 (636, 0.028571428571428567),
 (637, 0.052796367734845466),
 (638, 0.03450327796711771),
 (639, 0.0),
 (640, 0.0515539262226467),
 (641, 0.0),
 (642, 0.0),
 (643, 0.10690449676496976),
 (644, 0.05797710356524483),
 (645, 0.04829452884162951),
 (646, 0.057142857142857134),
 (647, 0.052164053095730106),
 (648, 0.03253000243161777),
 (649, 0.0),
 (650, 0.0),
 (651, 0.0),
 (652, 0.024397501823713332),
 (653, 0.12298800925361816),
 (654, 0.089554732567929),
 (655, 0.026082026547865053),
 (656, 0.0),
 (657, 0.037332669647327864),
 (658, 0.05413319619607667),
 (659, 0.027066598098038335),
 (660, 0.10350983390135313),
 (661, 0.1690308509457033),
 (662, 0.0),
 (663, 0.0),
 (664, 0.06506000486323554),
 (665, 0.07476671794188401),
 (666, 0.052164053095730106),
 (667, 0.0),
 (668, 0.07049073768502413),
 (669, 0.036037498507822355),
 (670, 0.017817416127494958),
 (671, 0.05413319619607667),
 (672, 0.05797710356524483),
 (673, 0.023218173010628604),
 (674, 0.07733088933397005),
 (675, 0.0515539262226467),
 (676, 0.033149677206589796),
 (677, 0.02742042485535409),
 (678, 0.06277648205743444),
 (679, 0.0),
 (680, 0.08451542547285165),
 (681, 0.035245368842512066),
 (682, 0.024147264420814756),
 (683, 0.0515539262226467),
 (684, 0.0),
 (685, 0.03779644730092272),
 (686, 0.0),
 (687, 0.11952286093343935),
 (688, 0.05039526306789696),
 (689, 0.0),
 (690, 0.029424494316824985),
 (691, 0.10141851056742199),
 (692, 0.12073632210407378),
 (693, 0.0),
 (694, 0.02366905341655754),
 (695, 0.06900655593423542),
 (696, 0.0),
 (697, 0.0),
 (698, 0.02366905341655754),
 (699, 0.0),
 (700, 0.030860669992418377),
 (701, 0.06506000486323554),
 (702, 0.024397501823713332),
 (703, 0.02080625946441197),
 (704, 0.07396705090823068),
 (705, 0.025482359571881275),
 (706, 0.026082026547865053),
 (707, 0.0),
 (708, 0.025482359571881275),
 (709, 0.0),
 (710, 0.0447773662839645),
 (711, 0.06629935441317959),
 (712, 0.0),
 (713, 0.027788500718836418),
 (714, 0.0),
 (715, 0.1057361065275362),
 (716, 0.035245368842512066),
 (717, 0.0),
 (718, 0.04643634602125721),
 (719, 0.0),
 (720, 0.02742042485535409),
 (721, 0.033149677206589796),
 (722, 0.0),
 (723, 0.026398183867422733),
 (724, 0.026082026547865053),
 (725, 0.0),
 (726, 0.0),
 (727, 0.036454130828824455),
 (728, 0.07559289460184544),
 (729, 0.0),
 (730, 0.019262853213235485),
 (731, 0.05484084971070818),
 (732, 0.0791945516022682),
 (733, 0.0447773662839645),
 (734, 0.05039526306789696),
 (735, 0.04984447862792268),
 (736, 0.033149677206589796),
 (737, 0.08017837257372731),
 (738, 0.0),
 (739, 0.03877833671647406),
 (740, 0.13199091933711365),
 (741, 0.05884898863364997),
 (742, 0.03450327796711771),
 (743, 0.02577696311132335),
 (744, 0.06761234037828133),
 (745, 0.06277648205743444),
 (746, 0.08696565534786725),
 (747, 0.02366905341655754),
 (748, 0.03779644730092272),
 (749, 0.0),
 (750, 0.05096471914376255),
 (751, 0.03779644730092272),

In [46]:
def recommend(movie):
    index = new[new['title'] == movie].index[0]
    distances = sorted(list(enumerate(similarity[index])),reverse=True,key = lambda x: x[1])
    for i in distances[1:6]:
        print(new.iloc[i[0]].title)
#         print(i[0])

In [47]:
recommend('Gandhi')

Gandhi, My Father
The Wind That Shakes the Barley
A Passage to India
Guiana 1838
Ramanujan

In [48]:
recommend("Pirates of the Caribbean: At World's End")

Pirates of the Caribbean: Dead Man's Chest
Pirates of the Caribbean: The Curse of the Black Pearl
Pirates of the Caribbean: On Stranger Tides
20,000 Leagues Under the Sea
Puss in Boots

In [ ]:
recommend("Pirates of the Caribbean: At World's End")